[build]
  publish = "packages/www/public/"
  command = "yarn workspace www build && cd functions/graphql && yarn"
  functions = "functions/"

[build.environment]
  GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES = "true"

[dev]
  framework = "#custom"
  command = "yarn workspace www develop"
  targetPort = 8000
  publish = "packages/public"